mode: rule
mixed-port: 7890
allow-lan: true
bind-address: '*'
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
secret: ''
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
    - weatherapi.market.xiaomi.com
  nameserver:
    - 'quic://223.5.5.5:853#直连'
    - 'https://1.12.12.12:443/dns-query#直连'
  nameserver-policy:
    'geosite:gfw': 
      - 'quic://94.140.14.14:853#选择'
      - 'tls://1.1.1.1:853#选择'
      - 'tls://8.8.8.8:853#选择'

tcp-concurrent: true
