mode: rule
mixed-port: 7897
allow-lan: true
log-level: info
#secret: ''
external-controller: 127.0.0.1:9097
dns:
  enabled: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  use-hosts: true
  nameserver:
    - 'https://1.1.1.1/dns-query#代理&h3=true'
    - 'https://8.8.8.8/dns-query#代理&h3=true'
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query#h3=true'
  nameserver-policy:
    "geosite:cn": 'https://223.5.5.5/dns-query#h3=true'
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "dns.msftncsi.com"
  - "www.msftncsi.com"
  - "www.msftconnecttest.com"
  - "*.srv.nintendo.net"
  - "*.stun.playstation.net"
  - "xbox.*.microsoft.com"
  - "*.xboxlive.com"
  - "*.lan"
  - "localhost.ptlogin2.qq.com"

tcp-concurrent: true
unified-delay: true

rules:
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,bfv.exe,代理
  - PROCESS-NAME,EADesktop.exe,代理
  - PROCESS-NAME,EABackgroundService.exe,代理
  - PROCESS-NAME,QtWebEngineProcess.exe,代理
  - PROCESS-NAME,EACefSubProcess.exe,代理
  - DOMAIN,bam.nr-data.net,代理
  - DOMAIN,pin-em.data.ea.com,代理
  - DOMAIN,sdk.split.io,代理
  - DOMAIN,gateway.ea.com,代理
  - DOMAIN,chat.openai.com.cdn.cloudflare.net,代理
  - DOMAIN-SUFFIX,mqmqgo.pp.ua,代理
  - DOMAIN-SUFFIX,mqmqgo.cloudns.eu,代理
  - DOMAIN-SUFFIX,mqmqgo.top,代理
  - PROCESS-NAME,HeavenBurnsRed.exe,代理
  - domain,api-ap.heaven-burns-red.wfs.games,代理
  - PROCESS-NAME,Photoshop.exe,REJECT
