mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: true
tcp-concurrent: true
dns:
  enable: true
  prefer-h3: false
  use-hosts: false
  use-system-hosts: false
  respect-rules: false
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  nameserver:
    - system
