mixed-port: 7890
allow-lan: true
bind-address: '*'
ipv6: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
  enabled: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  nameserver:
    - 'https://cloudflare-dns.com/dns-query#选择&h3=true'
    - 'https://dns.google/dns-query#选择&h3=true'
  proxy-server-nameserver:
    - https://sm2.doh.pub/dns-query#h3=true
  nameserver-policy:
    'geosite:cn': https://sm2.doh.pub/dns-query#h3=true

tcp-concurrent: true
unified-delay: true
