mode: rule
mixed-port: 7890
allow-lan: true
bind-address: '*'
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
secret: ''
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
  nameserver:
    - 'quic://dns.adguard-dns.com#自动'
    - 'https://cloudflare-dns.com/dns-query#自动'
    - 'https://dns.google/dns-query#自动'
  proxy-server-nameserver:
    - 'quic://223.5.5.5:853#直连'
    - 'https://sm2.doh.pub/dns-query#直连'
  nameserver-policy:
    'geosite:cn,private': 
      - 'quic://223.5.5.5:853#直连'
      - 'https://sm2.doh.pub/dns-query#直连'

tcp-concurrent: true
unified-delay: true
