mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
tcp-concurrent: true
dns:
  enable: true
  prefer-h3: false
  use-hosts: true
  use-system-hosts: false
  respect-rules: false
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  nameserver:
    - tls://1dot1dot1dot1.cloudflare-dns.com#PROXY
    - tls://dns.google#PROXY
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#DIRECT
    - https://doh.pub/dns-query#DIRECT
  direct-nameserver:
    - https://dns.alidns.com/dns-query#DIRECT
    - https://doh.pub/dns-query#DIRECT
hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  doh.pub: [1.12.12.21, 120.53.53.53]
