dns:
  enabled: true
  ipv6: true
  listen: 127.0.0.1:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
  use-hosts: true
  nameserver:
    - 'https://cloudflare-dns.com/dns-query#选择'
    - 'https://dns.google/dns-query#选择'
    - 'https://chrome.cloudflare-dns.com/dns-query#选择'
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
   geosite:cn,private:
    - https://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query
    - https://doh.pub/dns-query
