mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
ipv6: true
tcp-concurrent: true
dns:
  enable: true
  use-hosts: true
  respect-rules: false
  listen: 0.0.0.0:53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  nameserver:
    - tls://1.1.1.1:853#PROXY
    - tls://8.8.8.8:853#PROXY
  proxy-server-nameserver:
    - quic://dns.alidns.com:853#DIRECT
    - https://sm2.doh.pub:443/dns-query#DIRECT
  direct-nameserver:
    - quic://dns.alidns.com:853#DIRECT
    - https://sm2.doh.pub:443/dns-query#DIRECT
hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  sm2.doh.pub: 106.55.91.174
