dns:
  use-hosts: true
  proxy-server-nameserver:
    - quic://dns.alidns.com:853#直连
    - https://sm2.doh.pub:443/dns-query#直连
  direct-nameserver:
    - quic://dns.alidns.com:853#直连
    - https://sm2.doh.pub:443/dns-query#直连
  nameserver:
    - quic://dns.adguard-dns.com:853#选择
    - tls://1dot1dot1dot1.cloudflare-dns.com:853#选择
    - tls://dns.google:853#选择
hosts:
  dns.alidns.com: [223.5.5.5, 223.6.6.6]
  sm2.doh.pub: 106.55.91.174
  dns.adguard-dns.com: [94.140.14.14, 94.140.15.15]
  1dot1dot1dot1.cloudflare-dns.com: [1.1.1.1, 1.0.0.1]
  dns.google: [8.8.8.8, 8.8.4.4]
  
