mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: true
tcp-concurrent: true
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - "udp://any:53"
    - "tcp://any:53"
  device: Mihomo
  mtu: 9000
  strict-route: true
dns:
  enable: true
  use-hosts: false
  use-system-hosts: false
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
  nameserver:
    - system
