mode: rule
mixed-port: 7890
allow-lan: true
bind-address: '*'
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
secret: ''
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'
  nameserver:
    - 'quic://94.140.14.14#选择'
    - 'https://1.1.1.1/dns-query#选择'
    - 'https://8.8.8.8/dns-query#选择'
  proxy-server-nameserver:
    - 'quic://223.5.5.5#直连'
    - 'https://1.12.12.12/dns-query#直连'
  nameserver-policy:
    'geosite:cn,private': 
      - 'quic://223.5.5.5#直连'
      - 'https://1.12.12.12/dns-query#直连'

tcp-concurrent: true
unified-delay: true
